nginx:
  build: ./nginx
  hostname: nginx
  net: hadoop
  container_name: nginx
  ports:
    - "8080:80"

namenode:
  image: leismile/hadoop-namenode:1.1.0-hadoop2.7.2-java8
  hostname: namenode
  container_name: namenode
  domainname: hadoop
  net: hadoop
  volumes:
    - ./data/namenode:/hadoop/dfs/name
  environment:
    - CLUSTER_NAME=test
  env_file:
    - ./hadoop.env

resourcemanager:
  image: leismile/hadoop-resourcemanager:1.1.0-hadoop2.7.2-java8
  hostname: resourcemanager
  container_name: resourcemanager
  domainname: hadoop
  net: hadoop
  env_file:
    - ./hadoop.env

historyserver:
  image: leismile/hadoop-historyserver:1.1.0-hadoop2.7.2-java8
  hostname: historyserver
  container_name: historyserver
  domainname: hadoop
  net: hadoop
  volumes:
    - ./data/historyserver:/hadoop/yarn/timeline
  env_file:
    - ./hadoop.env

nodemanager1:
  image: leismile/hadoop-nodemanager:1.1.0-hadoop2.7.2-java8
  hostname: nodemanager1
  container_name: nodemanager1
  domainname: hadoop
  net: hadoop
  env_file:
    - ./hadoop.env

datanode1:
  image: leismile/hadoop-datanode:1.1.0-hadoop2.7.2-java8
  hostname: datanode1
  container_name: datanode1
  domainname: hadoop
  net: hadoop
  volumes:
    - ./data/datanode1:/hadoop/dfs/data
  env_file:
    - ./hadoop.env

datanode2:
  image: leismile/hadoop-datanode:1.1.0-hadoop2.7.2-java8
  hostname: datanode2
  container_name: datanode2
  domainname: hadoop
  net: hadoop
  volumes:
    - ./data/datanode2:/hadoop/dfs/data
  env_file:
    - ./hadoop.env

datanode3:
  image: leismile/hadoop-datanode:1.1.0-hadoop2.7.2-java8
  hostname: datanode3
  container_name: datanode3
  domainname: hadoop
  net: hadoop
  volumes:
    - ./data/datanode3:/hadoop/dfs/data
  env_file:
    - ./hadoop.env
