version: "2"

services:
  namenode:
    image: leismile/hadoop-namenode:1.1.0-hadoop2.7.2-java8
    container_name: namenode
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
  
  resourcemanager:
    image: leismile/hadoop-resourcemanager:1.1.0-hadoop2.7.2-java8
    container_name: resourcemanager
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3      
    env_file:
      - ./hadoop.env
  
  historyserver:
    image: leismile/hadoop-historyserver:1.1.0-hadoop2.7.2-java8
    container_name: historyserver
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3      
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env
  
  nodemanager1:
    image: leismile/hadoop-nodemanager:1.1.0-hadoop2.7.2-java8
    container_name: nodemanager1
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3      
    env_file:
      - ./hadoop.env
  
  datanode1:
    image: leismile/hadoop-datanode:1.1.0-hadoop2.7.2-java8
    container_name: datanode1
    depends_on:
      - namenode
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
  
  datanode2:
    image: leismile/hadoop-datanode:1.1.0-hadoop2.7.2-java8
    container_name: datanode2
    depends_on:
      - namenode
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
  
  datanode3:
    image: leismile/hadoop-datanode:1.1.0-hadoop2.7.2-java8
    container_name: datanode3
    depends_on:
      - namenode
    volumes:
      - hadoop_datanode3:/hadoop/dfs/data
    env_file:
      - ./hadoop.env

volumes:
  hadoop_namenode:
  hadoop_datanode1:
  hadoop_datanode2:
  hadoop_datanode3:
  hadoop_historyserver:
